"""Merchant-week feature engineering for RiskLens.

Turns a raw merchant-week record (as generated by generate_synthetic_data.py
or scored live) into the flat feature set the rules engine and, later, the
Milestone 7 model consume. This module never reads or emits
label_high_loss_next_30d or latent_state_for_demo_only -- those are excluded
defensively even if present on the input row, per CLAUDE.md's separation of
policy/scoring from the hidden generation state.

See docs/MILESTONE_2_RULES_AND_FEATURES.md for the full feature catalogue
with formula, meaning, range, missing-value behavior, and rules/ML/both
usage for every feature below.
"""

from __future__ import annotations

import pandas as pd

LABEL_COLUMN = "label_high_loss_next_30d"
LATENT_STATE_COLUMN = "latent_state_for_demo_only"
EXCLUDED_INPUT_COLUMNS = {LABEL_COLUMN, LATENT_STATE_COLUMN}

RAW_INPUT_FIELDS = [
    "merchant_id",
    "week_start",
    "merchant_category",
    "merchant_age_days",
    "transaction_count_30d",
    "transaction_volume_30d",
    "transaction_volume_previous_30d",
    "refund_count_30d",
    "refund_rate_30d",
    "refund_rate_previous_30d",
    "chargeback_count_30d",
    "chargeback_rate_30d",
    "chargeback_rate_previous_30d",
    "top_dispute_reason_category",
    "delivery_evidence_coverage",
    "support_ticket_rate",
    "average_support_resolution_time_hours",
    "previous_review_outcome",
]

CHARGEBACK_RATIO_EPSILON = 0.002
CHARGEBACK_RATIO_CAP = 50.0

SUPPORT_RESOLUTION_BAND_LOW_MAX_HOURS = 24.0
SUPPORT_RESOLUTION_BAND_MEDIUM_MAX_HOURS = 48.0
SUPPORT_RESOLUTION_NORMALIZATION_HOURS = 100.0

MERCHANT_AGE_BAND_NEW_MAX_DAYS = 90
MERCHANT_AGE_BAND_GROWING_MAX_DAYS = 365

# name -> (formula, meaning, range, missing_value_behavior, used_by)
FEATURE_CATALOGUE = [
    {
        "name": "refund_rate_change",
        "formula": "refund_rate_30d - refund_rate_previous_30d",
        "meaning": "Absolute change in refund rate versus the merchant's own prior 30-day window.",
        "range": "Typically -1.0 to 1.0; usually small in magnitude.",
        "missing_value_behavior": "0.0 if either input rate is missing (treated as no observed change).",
        "used_by": "both",
    },
    {
        "name": "chargeback_rate_change",
        "formula": "chargeback_rate_30d - chargeback_rate_previous_30d",
        "meaning": "Absolute change in chargeback rate versus the merchant's own prior 30-day window.",
        "range": "Typically -1.0 to 1.0; usually small in magnitude.",
        "missing_value_behavior": "0.0 if either input rate is missing.",
        "used_by": "both",
    },
    {
        "name": "transaction_volume_change",
        "formula": "(transaction_volume_30d - transaction_volume_previous_30d) / transaction_volume_previous_30d",
        "meaning": "Relative change in payment volume versus the merchant's own prior 30-day window.",
        "range": "Approximately -1.0 (volume dropped to zero) to arbitrarily large for volume spikes.",
        "missing_value_behavior": "0.0 if transaction_volume_previous_30d is zero or missing (avoids divide-by-zero).",
        "used_by": "ml",
    },
    {
        "name": "refund_to_chargeback_ratio",
        "formula": f"refund_rate_30d / chargeback_rate_30d, capped at {CHARGEBACK_RATIO_CAP}",
        "meaning": "How much more common refunds are than chargebacks for this merchant-week. High values suggest refund-driven (often legitimate-return) behavior rather than chargeback-driven loss risk.",
        "range": f"0 to {CHARGEBACK_RATIO_CAP} when computed; otherwise missing.",
        "missing_value_behavior": f"Missing (None) if chargeback_rate_30d < {CHARGEBACK_RATIO_EPSILON} — the ratio is not numerically stable when the denominator is this close to zero, so it is left unset rather than reported as a misleadingly large or small number ('where safe', per the Milestone 2 requirement).",
        "used_by": "ml",
    },
    {
        "name": "delivery_evidence_gap",
        "formula": "1 - delivery_evidence_coverage",
        "meaning": "How much delivery/fulfilment evidence is missing, as a fraction. Higher means weaker evidence coverage.",
        "range": "0.0 to 1.0.",
        "missing_value_behavior": "Not computed if delivery_evidence_coverage is missing; feature is omitted.",
        "used_by": "both",
    },
    {
        "name": "support_resolution_hours_normalized",
        "formula": f"min(average_support_resolution_time_hours, {SUPPORT_RESOLUTION_NORMALIZATION_HOURS}) / {SUPPORT_RESOLUTION_NORMALIZATION_HOURS}",
        "meaning": "Support resolution time scaled to roughly 0-1 for use in a linear model, clipped so a small number of extreme outliers don't dominate.",
        "range": "0.0 to 1.0.",
        "missing_value_behavior": "Not computed if the raw field is missing; feature is omitted.",
        "used_by": "ml",
    },
    {
        "name": "support_resolution_risk_band",
        "formula": f"'low' if hours < {SUPPORT_RESOLUTION_BAND_LOW_MAX_HOURS} else 'medium' if hours < {SUPPORT_RESOLUTION_BAND_MEDIUM_MAX_HOURS} else 'high'",
        "meaning": "Categorical band version of support resolution time, for rule readability (rules compare against the raw hours field directly; this band is a documentation/analyst-explanation convenience, not a separate rule input).",
        "range": "One of: low, medium, high.",
        "missing_value_behavior": "Not computed if the raw field is missing; feature is omitted.",
        "used_by": "rules",
    },
    {
        "name": "support_ticket_rate",
        "formula": "passthrough of the raw support_ticket_rate field",
        "meaning": "Support tickets opened per transaction in the trailing 30 days.",
        "range": "0.0 to roughly 0.2 in this synthetic dataset.",
        "missing_value_behavior": "Passed through as-is; not imputed.",
        "used_by": "both",
    },
    {
        "name": "merchant_age_days",
        "formula": "passthrough of the raw merchant_age_days field",
        "meaning": "Days since merchant onboarding, as of week_start.",
        "range": "Non-negative integer.",
        "missing_value_behavior": "Passed through as-is; not imputed.",
        "used_by": "ml",
    },
    {
        "name": "merchant_age_band",
        "formula": f"'new' if age_days < {MERCHANT_AGE_BAND_NEW_MAX_DAYS} else 'growing' if age_days < {MERCHANT_AGE_BAND_GROWING_MAX_DAYS} else 'established'",
        "meaning": "Categorical age band, for analyst-facing readability alongside the raw age.",
        "range": "One of: new, growing, established.",
        "missing_value_behavior": "Not computed if the raw field is missing; feature is omitted.",
        "used_by": "rules",
    },
    {
        "name": "transaction_count_30d",
        "formula": "passthrough of the raw transaction_count_30d field",
        "meaning": "Trailing-30-day transaction count; provides scale context for the rate-based features.",
        "range": "Non-negative integer.",
        "missing_value_behavior": "Passed through as-is; not imputed.",
        "used_by": "both",
    },
    {
        "name": "merchant_category",
        "formula": "passthrough of the raw merchant_category field",
        "meaning": (
            "Descriptive segmentation only (per the 2026-08-22 rescope decision to drop declared-vs-observed "
            "category mismatch from Phase 1 entirely). Included as a feature because baseline refund/return norms "
            "genuinely differ by category (e.g. apparel vs. digital_services), so it is a legitimate control "
            "variable, not a profile-mismatch signal — no 'observed_category' counterpart exists or is compared "
            "against it anywhere in this codebase."
        ),
        "range": "One of: apparel, electronics, grocery, travel, digital_services, food_delivery.",
        "missing_value_behavior": "Passed through as-is; not imputed. One-hot encoding happens at model-training time (Milestone 7), not here.",
        "used_by": "ml",
    },
    {
        "name": "previous_review_outcome",
        "formula": "passthrough of the raw previous_review_outcome field",
        "meaning": (
            "The outcome of the merchant's most recent PRIOR review, if any — known before this week's "
            "prediction date, so it is time-safe by construction (it never reflects a review triggered by "
            "the current row). Included because a prior confirmed-risk outcome is a legitimate repeat-offender "
            "signal. Known synthetic-generation simplification, documented in the Milestone 1 data-quality "
            "report: this field is currently sampled independently per week from state-conditioned weights "
            "rather than tracking an actual persistent review history — it does not leak this week's outcome, "
            "but it is not yet a fully realistic time series either."
        ),
        "range": "One of: none, confirmed_risk, false_positive, inconclusive, operational_issue.",
        "missing_value_behavior": "Passed through as-is; not imputed.",
        "used_by": "both",
    },
]

FEATURE_NAMES = [f["name"] for f in FEATURE_CATALOGUE]


def _support_resolution_band(hours: float) -> str:
    if hours < SUPPORT_RESOLUTION_BAND_LOW_MAX_HOURS:
        return "low"
    if hours < SUPPORT_RESOLUTION_BAND_MEDIUM_MAX_HOURS:
        return "medium"
    return "high"


def _merchant_age_band(age_days: float) -> str:
    if age_days < MERCHANT_AGE_BAND_NEW_MAX_DAYS:
        return "new"
    if age_days < MERCHANT_AGE_BAND_GROWING_MAX_DAYS:
        return "growing"
    return "established"


def _refund_to_chargeback_ratio(refund_rate: float, chargeback_rate: float) -> float | None:
    if chargeback_rate is None or chargeback_rate < CHARGEBACK_RATIO_EPSILON:
        return None
    return round(min(refund_rate / chargeback_rate, CHARGEBACK_RATIO_CAP), 4)


def compute_features(row: dict) -> dict:
    """Compute the feature dict for a single merchant-week row (plain dict in, plain dict out).

    Defensively drops label_high_loss_next_30d and latent_state_for_demo_only
    even if present on the input -- they must never reach the feature output.
    """
    row = {k: v for k, v in row.items() if k not in EXCLUDED_INPUT_COLUMNS}

    refund_rate_30d = row.get("refund_rate_30d")
    refund_rate_previous_30d = row.get("refund_rate_previous_30d")
    chargeback_rate_30d = row.get("chargeback_rate_30d")
    chargeback_rate_previous_30d = row.get("chargeback_rate_previous_30d")
    volume_30d = row.get("transaction_volume_30d")
    volume_previous_30d = row.get("transaction_volume_previous_30d")
    evidence_coverage = row.get("delivery_evidence_coverage")
    resolution_hours = row.get("average_support_resolution_time_hours")
    age_days = row.get("merchant_age_days")

    features: dict = {}

    if refund_rate_30d is not None and refund_rate_previous_30d is not None:
        features["refund_rate_change"] = round(refund_rate_30d - refund_rate_previous_30d, 4)
    else:
        features["refund_rate_change"] = 0.0

    if chargeback_rate_30d is not None and chargeback_rate_previous_30d is not None:
        features["chargeback_rate_change"] = round(chargeback_rate_30d - chargeback_rate_previous_30d, 4)
    else:
        features["chargeback_rate_change"] = 0.0

    if volume_30d is not None and volume_previous_30d:
        features["transaction_volume_change"] = round((volume_30d - volume_previous_30d) / volume_previous_30d, 4)
    else:
        features["transaction_volume_change"] = 0.0

    features["refund_to_chargeback_ratio"] = _refund_to_chargeback_ratio(refund_rate_30d, chargeback_rate_30d)

    if evidence_coverage is not None:
        features["delivery_evidence_gap"] = round(1 - evidence_coverage, 4)

    if resolution_hours is not None:
        features["support_resolution_hours_normalized"] = round(min(resolution_hours, SUPPORT_RESOLUTION_NORMALIZATION_HOURS) / SUPPORT_RESOLUTION_NORMALIZATION_HOURS, 4)
        features["support_resolution_risk_band"] = _support_resolution_band(resolution_hours)

    if "support_ticket_rate" in row:
        features["support_ticket_rate"] = row["support_ticket_rate"]

    if age_days is not None:
        features["merchant_age_days"] = age_days
        features["merchant_age_band"] = _merchant_age_band(age_days)

    if "transaction_count_30d" in row:
        features["transaction_count_30d"] = row["transaction_count_30d"]

    if "merchant_category" in row:
        features["merchant_category"] = row["merchant_category"]

    if "previous_review_outcome" in row:
        features["previous_review_outcome"] = row["previous_review_outcome"]

    return features


def compute_feature_frame(df: pd.DataFrame) -> pd.DataFrame:
    """Vectorized equivalent of compute_features for a whole dataframe."""
    df = df.drop(columns=[c for c in EXCLUDED_INPUT_COLUMNS if c in df.columns])

    out = pd.DataFrame(index=df.index)
    out["refund_rate_change"] = (df["refund_rate_30d"] - df["refund_rate_previous_30d"]).round(4)
    out["chargeback_rate_change"] = (df["chargeback_rate_30d"] - df["chargeback_rate_previous_30d"]).round(4)

    safe_prev_volume = df["transaction_volume_previous_30d"].replace(0, pd.NA)
    out["transaction_volume_change"] = ((df["transaction_volume_30d"] - df["transaction_volume_previous_30d"]) / safe_prev_volume).fillna(0.0).round(4)

    ratio = df["refund_rate_30d"] / df["chargeback_rate_30d"].where(df["chargeback_rate_30d"] >= CHARGEBACK_RATIO_EPSILON)
    out["refund_to_chargeback_ratio"] = ratio.clip(upper=CHARGEBACK_RATIO_CAP).round(4)

    out["delivery_evidence_gap"] = (1 - df["delivery_evidence_coverage"]).round(4)
    out["support_resolution_hours_normalized"] = (df["average_support_resolution_time_hours"].clip(upper=SUPPORT_RESOLUTION_NORMALIZATION_HOURS) / SUPPORT_RESOLUTION_NORMALIZATION_HOURS).round(4)
    out["support_resolution_risk_band"] = df["average_support_resolution_time_hours"].apply(_support_resolution_band)
    out["support_ticket_rate"] = df["support_ticket_rate"]
    out["merchant_age_days"] = df["merchant_age_days"]
    out["merchant_age_band"] = df["merchant_age_days"].apply(_merchant_age_band)
    out["transaction_count_30d"] = df["transaction_count_30d"]
    out["merchant_category"] = df["merchant_category"]
    out["previous_review_outcome"] = df["previous_review_outcome"]

    return out
